### ISSUE TITLE
Fix copy-dashboard and set-defaultdashboard

### ISSUE THREAD

**Issue by mzball-dt** [mzball-dt/utils#9]
The two dashboard scripts have several bugs.

## copy-dashboard.ps1

* [x]  Does not check token scopes for the source environment. It checks the source token with the destination environment which results in an error
* [x] Does not remove the id and owner from a copied dashboard, resulting in an error when pushing it into the destination

## set-defaultDashboard.ps1

* [x]  Same as the first above: Does not check token scopes for the source environment. It checks the source token with the destination environment which results in an error
* [ ] Confirm that the owner prop doesn't also need to be removed

**Comment by mzball-dt** [comment]
#10 does some work towards this

**Comment by adrian-chen-au** [comment]
Not sure why I put the id and owner clean up within the Dashboard name condition XD 
Also surprised you kept the envUrl variable name 👍
